spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-99H2OMK\SQLEXPRESS;encrypt=true;trustServerCertificate=true;databaseName=CompanyDB
    username: sa
    password: admin123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
